# Generated by Django 3.0.1 on 2021-03-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210322_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='c++.png', upload_to='profile_pictures'),
        ),
    ]
